# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="sieves"
version="${file.jarVersion}"
displayName="Sieves"
credits="dooZyz"
authors="dooZyz"
description='''
Automate shit
'''
[[dependencies.sieves]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sieves]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"
